variables:
    DOCKER_IMAGE: aracompany1455/arames:of

stages:
    - test
    - lint
    - build

testing:
    stage: test
    image: node:16
    before_script:
        - mv .env.template .env
        - npm set registry http://$IPADDRESS:$NPM_PORT
        - npm ci
    script:
        - npm run test
    rules:
        - if: '$CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
          allow_failure: false
        - if: '$CI_COMMIT_BRANCH != "master"'
          allow_failure: true

linting:
    stage: lint
    image: node:16
    before_script:
        - mv .env.template .env
        - npm set registry http://$IPADDRESS:$NPM_PORT
        - npm ci
    script:
        - npm run lint
    rules:
        - if: '$CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
          allow_failure: false
        - if: '$CI_COMMIT_BRANCH != "master"'
          allow_failure: true

building:
    stage: build
    image: docker:23.0.1-dind
    services:
        - docker:23.0.1-dind
    variables:
        DOCKER_TLS_CERTDIR: ''
        DOCKER_HOST: 'tcp://docker:2375'
    before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    script:
        - docker build -t "$DOCKER_IMAGE" .
        - docker push "$DOCKER_IMAGE"
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
