version: '3.3'
services:
    auth_db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'fabcom'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - ./auth_data:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10

    srv:
        image: registry.gitlab.com/aracompany/fabcom/auth:master
        restart: always
        environment:
            NODE_ENV: 'production'
            PORT: '3000'
            DATABASE_URL: 'mysql://root:password@auth_db/fabcom'
            JWT_SECRET: 'secret'
        ports:
            - '127.0.0.1:3000:3000'
        depends_on:
            db:
                condition: service_healthy
        entrypoint: ['/bin/sh', '-c', 'npx prisma migrate deploy && npm start']

volumes:
    auth_data:
