version: '3.3'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'fabcom'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '127.0.0.1:3306:3306'
