version: '3.3'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'fabcom'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '127.0.0.1:3306:3306'

    auth:
        image: registry.gitlab.com/aracompany/fabcom/auth
        restart: always
        environment:
            NODE_ENV: 'production'
            PORT: '3000'
            DATABASE_URL: 'mysql://user:password@db/fabcom'
            JWT_SECRET: 'secret'
        ports:
            - '127.0.0.1:3000:3000'
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
            interval: 10s
            timeout: 5s
            retries: 3
        command:
            ['npm', 'run', 'prisma:migrate:dev', '&&', 'npm', 'run', 'start']
